apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "crowdsec-firewall-bouncer-daemonset.fullname" . }}
  labels:
    {{- include "crowdsec-firewall-bouncer-daemonset.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "crowdsec-firewall-bouncer-daemonset.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "crowdsec-firewall-bouncer-daemonset.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      hostNetwork: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: "install-ipsets"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command:
            - /bin/sh
            - -c
            - |
              ./install_ipsets.sh && echo "done installing ipsets"
          securityContext:
            privileged: true
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            privileged: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: 
          - /bin/sh
          - -c
          - |
            cp crowdsec-firewall-bouncer.yaml crowdsec-firewall-bouncer.processed.yaml && \
            echo "\napi_key: $API_KEY" >> crowdsec-firewall-bouncer.processed.yaml && \
            crowdsec-firewall-bouncer -c crowdsec-firewall-bouncer.processed.yaml

          env:
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: {{.Values.existingSecretName}}
                key: "apikey"
          volumeMounts:
          - name: crowdsec-firewall-bouncer-config
            mountPath: /crowdsec-firewall-bouncer.yaml
            subPath: crowdsec-firewall-bouncer.yaml

      volumes:
      - name: crowdsec-firewall-bouncer-config
        configMap:
          name: crowdsec-firewall-bouncer-config
  
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

